name: Destroy Infrastructure

on:
  workflow_dispatch:
    inputs:
      confirm_destroy:
        description: "Type 'yes' to confirm infrastructure destruction"
        required: true

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: ${{ vars.AWS_REGION }}
  AWS_ROLE_ARN: arn:aws:iam::160071257600:role/iac-user-management-github-actions-oidc-role

jobs:
  destroy:
    name: Destroy Infrastructure
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ env.AWS_ROLE_ARN }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "~1.5.0"

      - name: Ensure destroy.sh is Executable
        run: chmod +x scripts/deployment/destroy.sh

      - name: Run Destroy Script
        if: ${{ github.event.inputs.confirm_destroy == 'yes' }}
        run: scripts/deployment/destroy.sh

      - name: Fail if not confirmed
        if: ${{ github.event.inputs.confirm_destroy != 'yes' }}
        run: echo "Destroy aborted. Please confirm by typing 'yes'."
